# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/bookedsocialservice:latest

  k6:
    runs-on: ubuntu-latest
    needs: docker

    services:
      bookservice:
        image: semwenders/bookedsocialservice:latest
        ports:
          - 8080:8080
          - 8081:8081
        env:
          ApplicationSettings:Neo4jConnection: mongodb://mongodb:27017
      neo4j:
        image: semwenders/neo4j
        ports:
          - 7687:7687

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        uses: grafana/k6-action@v0.3.1
        with:
          filename: LoadTest/scripts/GetFriends.js
        env:
          HOST_URL: "http://socialservice:8080"
